### ISSUE TITLE
Gdk Error when running okvis_app_synchronous

### ISSUE THREAD

**Issue by nushakrishnan** [smartroboticslab/okvis2#10]
Hello,

Firstly, thanks for the great work!

I am trying to run OKVIS2 via the okvis_app_synchronous on a custom dataset. On most sequences, I have an output csv that is generated. However, for a handful of them, I am facing the following error:

```bash
(OKVIS 2 Top View:564389): Gdk-ERROR **: 12:43:43.050: The program 'OKVIS 2 Top View' received an X Window System error. 
This probably reflects a bug in the program. The error was 'BadAccess (attempt to access private resource denied)'.
(Details: serial 273 error_code 10 request_code 130 (MIT-SHM) minor_code 1)
(Note to programmers: normally, X errors are reported asynchronously; 
that is, you will receive the error a while after causing it. 
To debug your program, run it with the GDK_SYNCHRONIZE environment variable to change this behavior. 
You can then get a meaningful backtrace from your debugger if you break on the gdk_x_error() function.)
```

I have attach an example log file and config for a sequence where I face this error. It would be great if I could receive some help debugging this.

Thanks a lot :)

[RW_1.log](https://github.com/user-attachments/files/18628952/RW_1.log)

The config looks like this:
```yaml
%YAML:1.0
cameras:
  - {T_SC: [0.9820368147243045, 0.18767332775862766, -0.0195554742756264, 0.01173384764470355,
      0.027050288624004923, -0.24259343396403743, -0.9697508482506703, -0.10854187086144126,
      -0.18674039844527482, 0.9518020528689457, -0.24331230084597255, 0.07667146912572737,
      0.0, 0.0, 0.0, 1.0], image_dimension: [780, 584], distortion_coefficients: [
      0.0, 0.0, 0.0, 0.0], distortion_type: equidistant, focal_length: [242.0631302984492,
      242.0631302984492], principal_point: [388.54488965547887, 292.59625228101345],
    camera_type: gray, slam_use: okvis}


# additional camera parameters
camera_parameters:
  timestamp_tolerance: 0.005   # [s] stereo frame out-of-sync tolerance
  image_delay: 0.00   # [s] timestamp_camera_correct = timestamp_camera - image_delay
  sync_cameras: [0]   # the cameras that will be synchronised
  online_calibration:   # some parameters to set the online 
    do_extrinsics: false     # Do we online-calibrate extrinsics?
    do_extrinsics_final_ba: false     # Do we calibrate extrinsics in final BA?
    sigma_r: 0.001     # T_SCi position prior stdev [m] 
    sigma_alpha: 0.05     # T_SCi orientation prior stdev [rad]

imu_parameters:
  use: true
  a_max: 78.448   # acceleration saturation [m/s^2]
  g_max: 1000.0   # gyro saturation [rad/s]
  sigma_g_c: 0.00017453292519943296   # gyro noise density [rad/s/sqrt(Hz)]
  sigma_a_c: 0.0007844799999999999   # accelerometer noise density [m/s^2/sqrt(Hz)]
  sigma_bg: 0.01   # gyro bias prior [rad/s]
  sigma_ba: 0.01   # accelerometer bias prior [m/s^2]
  sigma_gw_c: 0.00024437102728225855   # gyro drift noise density [rad/s^s/sqrt(Hz)]
  sigma_aw_c: 0.0064483304620110765   # accelerometer drift noise density [m/s^2/sqrt(Hz)]
    # Local gravity at 85748 Garching, Germany (latitude: 48.262768, elevation: 481m), according to https://www.sensorsone.com/local-gravity-calculator/
  g: 9.80600   # Earth's acceleration due to gravity [m/s^2]
  a0: [0.0, 0.0, 0.0]     # Accelerometer bias [m/s^2]
  g0: [0.0, 0.0, 0.0]     # initial gyro bias [rad/s]
    # tranform Body-Sensor (IMU)
  T_BS: [1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000,
    1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000]

# frontend: detection etc. 
frontend_parameters:
  detection_threshold: 38.0   #42.0 # detection threshold. By default the uniformity radius in pixels
  absolute_threshold: 150.0   # absolute Harris corner threshold (noise floor)
  matching_threshold: 60.0   # BRISK descriptor matching threshold
  octaves: 0   # number of octaves for detection. 0 means single-scale at highest resolution
  max_num_keypoints: 800   # restrict to a maximum of this many keypoints per image (strongest ones)
  keyframe_overlap: 0.60   # minimum field-of-view overlap
  use_cnn: true   # use the CNN (if available) to filter out dynamic content / sky
  parallelise_detection: true   # Run parallel detect & describe.
  num_matching_threads: 4   # Parallelise matching with this number of threads.

# estimator parameters
estimator_parameters:
  num_keyframes: 5   # number of keyframes in optimisation window
  num_loop_closure_frames: 5   # number of loop closure frames in optimisation window
  num_imu_frames: 3   # number of frames linked by most recent nonlinear IMU error terms
  do_loop_closures: true   # whether to do VI-SLAM or VIO
  do_final_ba: false   # Whether to run a full final BA
  enforce_realtime: true   # whether to limit the time budget for optimisation 
  realtime_min_iterations: 3   # minimum number of iterations always performed
  realtime_max_iterations: 10   # never do more than these, even if not converged
  realtime_time_limit: 0.035   # time budget for realtime optimisation [s]
  realtime_num_threads: 3   # number of threads for the realtime optimisation
  full_graph_iterations: 15   # don't do more than these for the full (background) optimisation
  full_graph_num_threads: 1   # number of threads for the full (background) optimisation

# some options for how and what to output
output_parameters:
  display_matches: false    # displays debug video and matches. May be slow.
  display_overhead: false   # debug overhead image. Is slow.
```
